name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Next.js app
        run: bun run build

      - name: Start Next.js
        run: bun run start &

      - name: Wait for Next.js to be ready
        run: |
          while ! nc -z localhost 3000; do
            sleep 1
          done

      - name: Run Cypress tests
        run: bun run test-cypress
