name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "version=$(bunx playwright --version | grep -oP 'Version \K[\d.]+')" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Cache Cypress binary
        id: cypress-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: bunx playwright install --with-deps

      - name: Build application
        run: bun run build

      - name: Start Next.js
        run: bun run start &

      - name: Wait for Next.js to be ready
        run: |
          while ! nc -z localhost 3000; do
            sleep 1
          done

      - name: Run Cypress tests
        run: bun run test-cypress

      - name: Run Playwright tests
        run: bun run test-playwright
